eureka:
  instance:
    prefer-ip-address: true
    # The below property will registry this microservice with eureka server as a client
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8084/eureka
